README.md, index.ts
Self-explanatory, just caught a couple snags in the README after recent changes.
=> update README to reflect changes: use "start" script, port 8545

.gitignore, app.ts, eip-712-helpers.ts, index.ts, jest.config.js, package-lock.json, package.json, test/eip712.test.ts, test/server.test.ts, test/utils.ts, tsconfig.json
This provides a /relay endpoint that can receive signed EIP-712 message and relay it to given near network.
=> Adding meta transaction relayer support

eip-712-helpers.ts, package-lock.json, package.json, test/eip712.test.ts, test/server.test.ts, test/utils.ts
This is change in accordance to with change in the nearcore: https://github.com/near/nearcore/pull/3845
=> Adding value to meta-tx and switch to use borsh serialization

README.md, config/betanet.yaml, config/default.yaml, config/localnet.yaml, config/mainnet.yaml, config/testnet.yaml, config/testnet_develop.yaml
- Changing signer_key to signerKey in config.
=> Minor fix in config yaml files

lib/indexer.js, src/indexer.ts
related issue https://github.com/aurora-is-near/aurora.js/issues/18
Blocked by https://github.com/aurora-is-near/aurora.js/pull/19
=> fix transaction indexing

.docker/docker-entrypoint-initdb.d/init.txt, etc/schema/functions/eth_getTransactionByBlockHashAndIndex.sql, etc/schema/functions/eth_getTransactionByBlockNumberAndIndex.sql, lib/indexer.js, lib/servers/database.js, src/indexer.ts, src/servers/database.ts, src/topics.ts
replacing the input value with `0x`. The null value breaks parsing the transaction format in `ethers.js`.
=> Fix null transaction.input value in the eth_getBlockByNumber()

lib/servers/database.js, package-lock.json, package.json, src/servers/database.ts
=> fix genesis block handling

lib/indexer.js, lib/utils.d.ts, lib/utils.js, src/indexer.ts, src/utils.ts
=> fix empty blocks

.ci/setup.sh
Make "broker" field in config to be empty.
=> Fix broker-error in CI

package-lock.json, package.json
Waiting on https://github.com/aurora-is-near/aurora.js/pull/25 to be merged
=> Aurora.js with proper chunk mask filter

lib/app.js, lib/blacklist.js, src/app.ts
Add `X-AURORA-ERROR-CODE` HTTP response headers for the error code.
=> Add `X-Aurora-Error-Code` HTTP response headers for the error code.

lib/app.js, src/app.ts
Fix header error setup when there is no error.
=> Check error for null value

lib/app.js, src/app.ts
Assign `X-Aurora-Error-Code` Header only for `eth_sendRawTransaction`.
=> Assign `X-Aurora-Error-Code` Header only for `eth_sendRawTransaction`.

lib/app.js, lib/servers/database.js, src/app.ts, src/servers/database.ts
Add "X-Aurora-Result", "X-NEAR-Gas-Burned", and "X-NEAR-TX" HTTP response headers.
=>  Add "X-Aurora-Result", "X-NEAR-Gas-Burned", and "X-NEAR-Transaction-ID" HTTP response headers.

lib/servers/database.js, src/servers/database.ts, test/server.test.ts
Closes: https://github.com/aurora-is-near/aurora-relayer/issues/268
```
[
{
"id": 2,
"error": {
"code": -32603,
"message": "Internal Error - Unknown encoding: 16. Please report a bug at <https://github.com/aurora-is-near/aurora-relayer/issues>",
"data": {
"host": "localhost:8545",
"request_body": [
{
"method": "eth_newBlockFilter",
"params": [],
"id": 2
}
]
}
}
}
]
```
```
[
{
"id": 2,
"result": "0x5d87a89f047545e9bdcbf3bf639980eb"
}
]
```
Result of `SELECT eth_newBlockFilter($1::inet) AS id`, is an Buffer
```
data Result {
command: 'SELECT',
rowCount: 1,
oid: null,
rows: [ { id: <Buffer 90 4f a3 f4 13 45 4c 02 8c 57 3a cc e6 c6 05 38> } ],
fields: [
Field {
name: 'id',
tableID: 0,
columnID: 0,
dataTypeID: 17,
dataTypeSize: -1, …
```
=> Fix eth_newBlockFilter

lib/ws_server.js, package-lock.json, package.json, tsconfig.json
https://github.com/aurora-is-near/aurora-relayer/blob/0d2a452934f8a54385e7f7d243bfe296d41a0141/.docker/Dockerfile.endpoint#L1
Node 14 config:
https://github.com/tsconfig/bases/blob/main/bases/node14.json
Node 16 config:
https://github.com/tsconfig/bases/blob/main/bases/node16.json
=> Sync TS config with current Node.js

lib/topics.js, src/topics.ts, test/server.test.ts
Relative to: https://github.com/aurora-is-near/aurora-relayer/issues/289
```
{
"method": "eth_getLogs",
"id": 1,
"params": [
{
"address": "0x8BEc47865aDe3B172A928df8f990Bc7f2A3b9f79",
"fromBlock": "0x3ecdf57",
"toBlock": "0x3ece307",
"topics": [
[],
["0x000000000000000000000000fe28a27a95e51bb2604abd65375411a059371616"]
]
}
]
}
```
Before:
```
{
"id": 1,
"error": {
"code": -32603,
"message": "Internal Error - syntax error at or near \"AND\". Please report a bug at <https://github.com/aurora-is-near/aurora-relayer/issues>",
"data": {
"host": "localhost:8545",
"request_body": {
"method": "eth_getLogs",
"id": 1,
"params": [
{
"address": "0x8BEc47865aDe3B172A928df8f990Bc7f2A3b9f79",
"fromBlock": "0x3ecdf57",
"toBlock": "0x3ece307", …
```
=> Handle [] topics for eth_getLogs

lib/topics.d.ts, lib/topics.js, lib/ws_server.js, src/topics.ts, src/ws_server.ts, test/match_topics.test.ts
Relative to: https://github.com/aurora-is-near/aurora-relayer/issues/272
```
{
"id": 1,
"method": "eth_subscribe",
"params": [
"logs",
{
"topics": [
null,
"0x0000000000000000000000002cb45edb4517d5947afde3beabf95a582506858b"
]
}
]
}
```
```
{
"method": "eth_subscription",
"params": {
"result": {
"blockNumber": "0x3f53ff9",
"blockHash": "0xc96b8a379b0ea492f296aaddf42aedbc8395de58efd060c5fd879ca00b2c9d27",
"transactionIndex": "0x4",
"transactionHash": "0x8ca33ba916b45b27f1c25b192d6e0fcbc06f75d36275ebc45e5c09634fb7a423",
"logIndex": "0x30",
"address": "0x17cbd9c274e90c537790c51b4015a65cd015497e",
"topics": [
"0x8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925",
"0x00000000000000000000000018fef1b130b788fe74fa6d61b39374caed93b4f2", …
```
=> Topic filtering not honored via eth_subscribe

lib/config.d.ts, lib/config.js, lib/errors.d.ts, lib/errors.js, lib/servers/database.d.ts, lib/servers/database.js, lib/servers/skeleton.js, src/config.ts, src/errors.ts, src/servers/database.ts, src/servers/skeleton.ts
- Add minGasPrice to config for use in [partner-relayer-deploy](https://github.com/aurora-is-near/partner-relayer-deploy)
- If minGasPrice is undefined than it's set to 0
- Eth can be withdrawn from near-aurora mapped account on [ref.finance](https://app.ref.finance/account)
=> Add minGasPrice to config

.docker/docker-entrypoint-initdb.d/init.txt, README.md, etc/schema/functions/eth_getFilterChanges.sql, lib/servers/database.d.ts, lib/servers/database.js, package-lock.json, package.json, src/servers/database.ts
```
{
"method": "eth_newFilter",
"params": [
{
"address": ["0xC6e5185438e1730959c1eF3551059A3feC744E90"]
}
],
"id": 2
}
```
```
{
"method": "eth_getFilterChanges",
"params": ["0x2f3a627ff38f479d99301b6a486155c4"],
"id": 2
}
```
<details>
<summary>Response</summary>
```
{
"id": 2,
"result": [
{
"blockNumber": "0x407df3a",
"blockHash": "0x6f0e3ce8cd93b4c157fc11287c916bf20a28d5ab166183414daf616439d05696",
"transactionIndex": "0x0",
"transactionHash": "0x579a3bd4895103864a8e540884b987cf446a21330e9f3ddc6fb9f2ddf656c51f",
"logIndex": "0x0",
"address": "0x8f975ac6defd2c9d50c58babf4b1f880e6de7996",
"topics": "{\"\\\\x17eabd0a66fa631f7537cefdd5df6aa25d5ac904cf7596e958d43a75a00d0d68\",\"\\\\x0000000000000000000000000000000000000000000000000000000 …
```
=> eth_getFilterChanges changes

README.md
https://eth.wiki/json-rpc/API - was archived and stopped working
https://github.com/ethereum/wiki
Description from `ethereum.org` does not provide a full description of the methods
https://ethereum.org/en/developers/docs/apis/json-rpc
https://github.com/ethereum/execution-apis
https://ethereum.github.io/execution-apis/api-documentation/
=> Update RPC method links

.gitattributes, .github/CODEOWNERS
* Update code owners
* Remove ignoring of `*.js` and `package-lock.json`, useful to see what changes have been made to `*.js` and `package-lock.json`
=> Update the project template

lib/topics.js, src/topics.ts, test/rpc_methods/eth_getLogs.test.ts
Query:
```
{
"method": "eth_getLogs",
"params": [
{
"address": "0xddf079d2f486f1ba8d5cbc0900e6a12c6f91ff82",
"fromBlock": "0x57a3c01",
"toBlock": "0x57a3c01",
"topics": [
[]
]
}
],
"id": 2
}
```
Before:
```
{
"id": 2,
"error": {
"code": -32603,
"message": "Internal Error - syntax error at or near \"LIMIT\". Please report a bug at <https://github.com/aurora-is-near/aurora-relayer/issues>",
"data": {
"host": "192.168.1.6",
"cf-ray": "723780f857c1da6e-FRA",
"request_body": {
"method": "eth_getLogs",
"params": [
{
"address": "0xddf079d2f486f1ba8d5cbc0900e6a12c6f91ff82",
"fromBlock": "0x57a3c01",
"toBlock": "0x57a3c01",
"topics": [
[]
]
}
],
"id": 2
}
}
}
}
```
After:
```
{
"id": 2,
"result": [
{
"blockNumber": …
```
=> eth_getFilterLogs handle empty topics params

lib/topics.js, src/topics.ts
Improvements for https://github.com/aurora-is-near/aurora-relayer/pull/323
=> compileTopics improvement

lib/servers/database.d.ts, lib/servers/database.js, src/servers/database.ts
* Unify eth_getLogs and _getFilterChangesEvent methods
=> Unify eth_getLogs and _getFilterChangesEvent

lib/ws_server.js, src/ws_server.ts
Demo
```
$ wscat -c ws://localhost:8545
Connected (press CTRL+C to quit)
> {"jsonrpc":"2.0", "id": 1, "method": "eth_subscribe", "params": ["newHeads_debug"]}
< {"jsonrpc":"2.0","id":1,"result":"0x7d73a66fb6b46ec7d3fec7e63c0666a2"}
< {"jsonrpc":"2.0","subscription":"0x7d73a66fb6b46ec7d3fec7e63c0666a2","result":{"blockNumber":71106023}}
< {"jsonrpc":"2.0","subscription":"0x7d73a66fb6b46ec7d3fec7e63c0666a2","result":{"blockNumber":71106023}}
< {"jsonrpc":"2.0","subscription":"0x7d73a66fb6b46ec7d3fec7e63c0666a2","result":{"blockNumber":71106023}}
< {"jsonrpc":"2.0","subscription":"0x7d73a66fb6b46ec7d3fec7e63c0666a2","result":{"blockNumber":71106023}}
< {"jsonrpc":"2.0","subscription":"0x7d73a66fb6b46ec7d3fec7e63c0666a2","result":{"blockNumber":71106023}}
< …
```
=> Add debug information for ws eth_subscribe newHeads_debug

package-lock.json, package.json
Ignore all batch transactions with more than one transaction during indexing.
=> aurora.js update

lib/servers/database.js, lib/topics.js, package-lock.json, package.json, src/servers/database.ts, src/topics.ts, test/rpc_methods/eth_call.test.ts
```
{
"method": "eth_call",
"params": [
{
"data": "0xbb29998e000000000000000000000000f53cc0ef22a093436bb53478b6b3fa8922264a70",
"to": "0x4d0FcE38D795155b1A72e55423d3696d4aDff53b"
},
"latest"
],
"id": 2
}
```
```
{
"id": 2,
"error": {
"code": -32603,
"message": "Internal Error - The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received an instance of Object. Please report a bug at <https://github.com/aurora-is-near/aurora-relayer/issues>",
"data": {
"host": "r003.westcoast.us.testnet.internal.aurora.dev",
"cf-ray": "760c5f2920f3749d-LHR",
"request_body": {
"method": "eth_call",
"params": [
{
"data": "0xbb29998e000000000000000000000000f53cc0ef22a093436bb53478b6b3fa8922264a7 …
```
=> eth_call: handle negative cases

lib/servers/database.d.ts, lib/servers/database.js, src/servers/database.ts, test/rpc_methods/eth_getBalance.test.ts, test/rpc_methods/eth_getCode.test.ts, test/rpc_methods/eth_getStorageAt.test.ts, test/rpc_methods/eth_getTransactionCount.test.ts
Improve block param for:
- eth_getBalance
- eth_getCode
- eth_getStorageAt
- eth_getTransactionCount
=> Improve block param for eth methods
